name: Python CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout my project
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=5 $(git ls-files '*.py')

      - name: Run the tests with pytest
        run: |
          coverage run -m pytest --profile

      - name: Report the coverage
        run: |
          python -m coverage report

      - name: Launch the app
        run: |
          uvicorn application.main:app

      - name: Test the app with locust
        run: |
          locust --config=.locust.conf
